name: Odoo CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Odoo Tests
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:15
        env:
          POSTGRES_DB: odoo
          POSTGRES_USER: odoo
          POSTGRES_PASSWORD: odoo
        ports:
          - 5432:5432
        options: --health-cmd "pg_isready -U odoo" --health-interval 10s --health-retries 5 --health-timeout 5s

      odoo:
        image: odoo:18.0
        ports:
          - 8069:8069
        env:
          HOST: db
          USER: odoo
          PASSWORD: odoo
        options: --health-cmd "curl --fail http://localhost:8069 || exit 1" --health-interval 10s --health-retries 5

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Wait for PostgreSQL
        run: |
          until pg_isready -h localhost -p 5432 -U odoo; do
            echo "Waiting for PostgreSQL to start..."
            sleep 2
          done

      - name: Run Odoo Tests
        run: |
          docker exec $(docker ps -q -f ancestor=odoo:18.0) \
          odoo-bin --db_host=db --db_user=odoo --db_password=odoo --test-enable --init project_priority --stop-after-init
