name: Odoo CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Odoo Tests
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:15
        env:
          POSTGRES_DB: odoo
          POSTGRES_USER: odoo
          POSTGRES_PASSWORD: odoo
        ports:
          - 5432:5432
        options: --health-cmd "pg_isready -U odoo -d odoo" --health-interval 10s --health-retries 5 --health-timeout 5s

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install PostgreSQL Client
        run: sudo apt-get install -y postgresql-client

      - name: Wait for PostgreSQL to be Ready
        run: |
          echo "Waiting for PostgreSQL to be ready..."
          until pg_isready -h localhost -p 5432 -U odoo -d odoo; do
            echo "PostgreSQL is not ready yet. Retrying in 2 seconds..."
            sleep 2
          done
          echo "PostgreSQL is ready!"

      - name: Ensure PostgreSQL is Fully Ready
        run: |
          echo "Checking PostgreSQL readiness..."
          until docker exec $(docker ps -q -f ancestor=postgres:15) \
          pg_isready -U odoo -d odoo; do
            echo "Database still starting, waiting 5s..."
            sleep 5
          done
          echo "PostgreSQL is fully ready!"

      - name: Start Odoo in Minimal Mode
        run: |
          docker run -d --name odoo-test \
            --network="host
