name: Odoo CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint Python Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pylint
          
      - name: Run Flake8
        run: flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        
      - name: Run Pylint
        run: pylint **/*.py

  test:
    name: Run Odoo Tests
    runs-on: ubuntu-latest
    needs: lint
    
    services:
      db:
        image: postgres:15
        env:
          POSTGRES_DB: odoo
          POSTGRES_USER: odoo
          POSTGRES_PASSWORD: odoo
        ports:
          - 5432:5432
        container_name: db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        networks:
          - odoo-network

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create Odoo Network
        run: docker network create odoo-network

      - name: Start Odoo and Initialize Base Module
        run: |
          docker run -d --name odoo-test \
            --network odoo-network \
            -e DB_HOST=db \
            -e DB_USER=odoo \
            -e DB_PASSWORD=odoo \
            --memory=4g --memory-swap=4g \
            odoo:18.0 \
            -- --db_host=db \
               --db_port=5432 \
               --db_user=odoo \
               --db_password=odoo \
               --workers=2 \
               --max-cron-threads=1 \
               --limit-memory-soft=2684354560 \
               --limit-memory-hard=3758096384 \
               -i base \
               --stop-after-init

      - name: Copy Module to Odoo Container
        run: |
          docker cp . odoo-test:/mnt/extra-addons/project_priority
          
      - name: Run Odoo Tests
        run: |
          docker exec odoo-test odoo \
            --db_host=db \
            --db_port=5432 \
            --db_user=odoo \
            --db_password=odoo \
            --test-enable \
            --workers=2 \
            --max-cron-threads=1 \
            --limit-memory-soft=2684354560 \
            --limit-memory-hard=3758096384 \
            --stop-after-init \
            --log-level=test \
            -i project_priority

      - name: Cleanup
        if: always()
        run: |
          docker rm -f odoo-test
          docker network rm odoo-network

networks:
  odoo-network:
    driver: bridge