name: Odoo CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint and Static Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pylint odoo

      - name: Run Flake8 (PEP8 Checks)
        run: |
          flake8 .

      - name: Run Pylint (Odoo Code Quality)
        run: |
          pylint --disable=R,C,W project_priority || true  # Ignore non-critical warnings

  test:
    name: Run Odoo Tests
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Install Odoo and Dependencies
        run: |
          pip install --pre odoo
          pip install -r requirements.txt

      - name: Run Odoo Tests
        run: |
          odoo-bin --test-enable --init project_priority --stop-after-init

