name: Odoo CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint and Static Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pylint

      - name: Run Flake8 (PEP8 Checks)
        run: flake8 .

      - name: Run Pylint (Odoo Code Quality)
        run: pylint --disable=R,C,W project_priority || true  # Ignore non-critical warnings

  test:
    name: Run Odoo Tests
    runs-on: ubuntu-latest
    needs: lint

    services:
      odoo:
        image: odoo:18.0  # Use Odoo 18.0 image
        ports:
          - 8069:8069
        options: --health-cmd "curl --fail http://localhost:8069 || exit 1" --health-interval 10s --health-retries 5

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run Odoo Tests
        run: |
          docker exec $(docker ps -q -f ancestor=odoo:18.0) odoo-bin --test-enable --init project_priority --stop-after-init
