name: Odoo CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Odoo Tests
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:15
        env:
          POSTGRES_DB: odoo
          POSTGRES_USER: odoo
          POSTGRES_PASSWORD: odoo
        ports:
          - 5432:5432
        options: --health-cmd "pg_isready -U odoo -d odoo" --health-interval 10s --health-retries 5 --health-timeout 5s

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install PostgreSQL Client
        run: sudo apt-get install -y postgresql-client

      - name: Wait for PostgreSQL to be Ready
        run: |
          echo "Waiting for PostgreSQL to be ready..."
          until pg_isready -h localhost -p 5432 -U odoo -d odoo; do
            echo "PostgreSQL is not ready yet. Retrying in 2 seconds..."
            sleep 2
          done
          echo "PostgreSQL is ready!"

      - name: Ensure PostgreSQL is Fully Ready
        run: |
          echo "Checking PostgreSQL readiness..."
          until docker exec $(docker ps -q -f ancestor=postgres:15) \
          pg_isready -U odoo -d odoo; do
            echo "Database still starting, waiting 5s..."
            sleep 5
          done
          echo "PostgreSQL is fully ready!"

      - name: Start Odoo and Initialize Base Module
        run: |
          docker run -d --name odoo-test \
            --network="host" \
            -e HOST=db \
            -e USER=odoo \
            -e PASSWORD=odoo \
            --memory=2g --memory-swap=2g \
            odoo:18.0 bash -c "odoo --db_host=db --db_user=odoo --db_password=odoo \
            --workers=0 --max-cron-threads=0 --limit-memory-soft=512000000 --limit-memory-hard=768000000 -i base --stop-after-init"

      - name: Run Odoo Tests
        run: |
          docker exec odoo-test odoo \
            --db_host=db --db_user=odoo --db_password=odoo \
            --test-enable --stop-after-init --log-level=test

      - name: Cleanup
        if: always()
        run: docker rm -f odoo-test
